// ============================================================
// constants.js — v23：天体数据扩展 + 卫星详细信息
// ============================================================

export const SIM = {
  BASE_SPEED: 1.0,
  SPEED_STEP: 0.4,
  MIN_SPEED: 0.0,
  MAX_SPEED: 5.0,
  MAX_DELTA: 0.1,
  ROTATION_SPEED_SCALE: 0.03,
};

const SCALE = 10;

export const BODIES = {
  sun: {
    name: "Sun",
    nameZh: "太阳",
    size: 3.0,
    orbitRadius: 0,
    orbitSpeed: 0,
    orbitalIncl: 0,
    axialTilt: 7.25,
    selfRotationSpeed: (2 * Math.PI) / 25.05,
    type: "star",
    realAU: 0,
    realPeriod: 0,
    realRadius: 696340,
    color: "#fffbe0",
    emissiveHex: null,
    emissiveIntensity: 0,
    description:
      "G-type main-sequence star (G2V). Surface temp: 5,778 K. 99.86% of Solar System mass.",
    descriptionZh:
      "G型主序星（G2V）。表面温度 5,778 K。占太阳系总质量的 99.86%。",
    mass: 332900,
    gravity: 274,
    temperature: "5,778 K",
    atmosphere: "H (73%), He (25%), traces",
    atmosphereZh: "氢 (73%), 氦 (25%), 微量",
    moonCount: 8,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  mercury: {
    name: "Mercury",
    nameZh: "水星",
    size: 0.22,
    orbitRadius: 0.387 * SCALE,
    orbitSpeed: (2 * Math.PI) / 88.0,
    orbitalIncl: 7.0,
    axialTilt: 0.03,
    selfRotationSpeed: (2 * Math.PI) / 58.6,
    type: "planet",
    realAU: 0.387,
    realPeriod: 88.0,
    realRadius: 2440,
    color: "#b0a090",
    emissiveHex: "#3a3028",
    emissiveIntensity: 0.18,
    description:
      "Smallest planet. No atmosphere. Temperature range: -180°C to 430°C.",
    descriptionZh: "太阳系最小行星。无大气层。温差极大：-180°C 至 430°C。",
    mass: 0.055,
    gravity: 3.7,
    temperature: "-180 ~ 430 °C",
    atmosphere: "None (trace exosphere)",
    atmosphereZh: "无（微量外逸层）",
    moonCount: 0,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  venus: {
    name: "Venus",
    nameZh: "金星",
    size: 0.6,
    orbitRadius: 0.723 * SCALE,
    orbitSpeed: (2 * Math.PI) / 224.7,
    orbitalIncl: 3.4,
    axialTilt: 177.4,
    selfRotationSpeed: (2 * Math.PI) / 243.0,
    type: "planet",
    realAU: 0.723,
    realPeriod: 224.7,
    realRadius: 6052,
    color: "#e8d5a8",
    emissiveHex: "#5a4a28",
    emissiveIntensity: 0.22,
    description:
      "Hottest planet (462°C). Thick CO₂ atmosphere. Retrograde rotation.",
    descriptionZh: "太阳系最热行星（462°C）。浓厚二氧化碳大气。逆向自转。",
    mass: 0.815,
    gravity: 8.87,
    temperature: "462 °C（平均）",
    atmosphere: "CO₂ (96.5%), N₂ (3.5%)",
    atmosphereZh: "二氧化碳 (96.5%), 氮气 (3.5%)",
    moonCount: 0,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  earth: {
    name: "Earth",
    nameZh: "地球",
    size: 0.65,
    orbitRadius: 1.0 * SCALE,
    orbitSpeed: (2 * Math.PI) / 365.25,
    orbitalIncl: 0.0,
    axialTilt: 23.44,
    selfRotationSpeed: (2 * Math.PI) / 1.0,
    type: "planet",
    realAU: 1.0,
    realPeriod: 365.25,
    realRadius: 6371,
    color: "#1a6fb5",
    emissiveHex: "#0a2255",
    emissiveIntensity: 0.2,
    description:
      "Only known planet with life. 71% ocean. Atmosphere: N₂ 78%, O₂ 21%.",
    descriptionZh:
      "目前唯一已知孕育生命的行星。71% 被海洋覆盖。大气：氮气 78%、氧气 21%。",
    mass: 1.0,
    gravity: 9.81,
    temperature: "15 °C（平均）",
    atmosphere: "N₂ (78%), O₂ (21%), Ar (0.9%)",
    atmosphereZh: "氮气 (78%), 氧气 (21%), 氩气 (0.9%)",
    moonCount: 1,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  moon: {
    name: "Moon",
    nameZh: "月球",
    size: 0.18,
    orbitRadius: 1.8,
    orbitSpeed: (2 * Math.PI) / 27.3,
    orbitalIncl: 5.14,
    axialTilt: 6.68,
    selfRotationSpeed: (2 * Math.PI) / 27.3,
    type: "moon",
    realAU: 0,
    realPeriod: 27.3,
    realRadius: 1737,
    color: "#aaaaaa",
    emissiveHex: "#2a2a2a",
    emissiveIntensity: 0.12,
    description:
      "Earth only natural satellite. Tidally locked. Basaltic maria + anorthositic highlands.",
    descriptionZh:
      "地球唯一的天然卫星。潮汐锁定。月海玄武岩 + 高地斜长岩地形。",
    mass: 0.0123,
    gravity: 1.62,
    temperature: "-20 °C（平均）",
    atmosphere: "None (trace exosphere)",
    atmosphereZh: "无（微量外逸层）",
    moonCount: 0,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  mars: {
    name: "Mars",
    nameZh: "火星",
    size: 0.4,
    orbitRadius: 1.524 * SCALE,
    orbitSpeed: (2 * Math.PI) / 687.0,
    orbitalIncl: 1.85,
    axialTilt: 25.19,
    selfRotationSpeed: (2 * Math.PI) / 1.026,
    type: "planet",
    realAU: 1.524,
    realPeriod: 687.0,
    realRadius: 3390,
    color: "#c1440e",
    emissiveHex: "#401208",
    emissiveIntensity: 0.2,
    description: "Red Planet. Iron oxide surface. Olympus Mons (21.9 km).",
    descriptionZh: "红色星球。氧化铁地表。奥林帕斯山（21.9 km）。",
    mass: 0.107,
    gravity: 3.73,
    temperature: "-63 °C（平均）",
    atmosphere: "CO₂ (95%), N₂ (2.6%), Ar (1.9%)",
    atmosphereZh: "二氧化碳 (95%), 氮气 (2.6%), 氩气 (1.9%)",
    moonCount: 2,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  jupiter: {
    name: "Jupiter",
    nameZh: "木星",
    size: 1.8,
    orbitRadius: 5.203 * SCALE,
    orbitSpeed: (2 * Math.PI) / 4332.6,
    orbitalIncl: 1.3,
    axialTilt: 3.13,
    selfRotationSpeed: (2 * Math.PI) / 0.414,
    type: "planet",
    realAU: 5.203,
    realPeriod: 4332.6,
    realRadius: 69911,
    color: "#d4a574",
    emissiveHex: "#3a2210",
    emissiveIntensity: 0.15,
    description: "Largest planet. Great Red Spot: 350+ years. 95 known moons.",
    descriptionZh: "太阳系最大行星。大红斑持续 350+ 年。已知 95 颗卫星。",
    mass: 317.8,
    gravity: 24.79,
    temperature: "-110 °C（云顶）",
    atmosphere: "H₂ (89%), He (10%), CH₄, NH₃",
    atmosphereZh: "氢气 (89%), 氦气 (10%), 甲烷, 氨",
    moonCount: 95,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  saturn: {
    name: "Saturn",
    nameZh: "土星",
    size: 1.55,
    orbitRadius: 9.537 * SCALE,
    orbitSpeed: (2 * Math.PI) / 10759.2,
    orbitalIncl: 2.5,
    axialTilt: 26.73,
    selfRotationSpeed: (2 * Math.PI) / 0.444,
    type: "planet",
    realAU: 9.537,
    realPeriod: 10759.2,
    realRadius: 58232,
    color: "#e8d5a0",
    emissiveHex: "#5a4830",
    emissiveIntensity: 0.3,
    description:
      "Iconic ring system: D/C/B/A/F/G/E rings. Main rings span 1.24-2.27 Rs. Composition: >95% water ice particles (cm-m size). Thickness: <100m. Cassini Division gap between B and A rings.",
    descriptionZh:
      "标志性光环系统：D/C/B/A/F/G/E 环。主环跨度 1.24-2.27 土星半径。成分：95% 以上水冰颗粒（厘米至米级）。厚度 <100 米。B 环与 A 环之间为卡西尼缝隙。",
    mass: 95.16,
    gravity: 10.44,
    temperature: "-178 °C（云顶）",
    atmosphere: "H₂ (96%), He (3%), CH₄, NH₃",
    atmosphereZh: "氢气 (96%), 氦气 (3%), 甲烷, 氨",
    moonCount: 146,
    discovery: "Known since antiquity",
    discoveryZh: "自古已知",
  },
  uranus: {
    name: "Uranus",
    nameZh: "天王星",
    size: 0.95,
    orbitRadius: 19.19 * SCALE,
    orbitSpeed: (2 * Math.PI) / 30688.5,
    orbitalIncl: 0.77,
    axialTilt: 97.77,
    selfRotationSpeed: (2 * Math.PI) / 0.718,
    type: "planet",
    realAU: 19.19,
    realPeriod: 30688.5,
    realRadius: 25362,
    color: "#7ec8e3",
    emissiveHex: "#0a3040",
    emissiveIntensity: 0.18,
    description: "Ice giant. Rotates on its side (98°). Methane → cyan color.",
    descriptionZh: "冰巨星。自转轴倾斜 98° 侧躺运行。甲烷导致青蓝色外观。",
    mass: 14.54,
    gravity: 8.69,
    temperature: "-224 °C",
    atmosphere: "H₂ (83%), He (15%), CH₄ (2%)",
    atmosphereZh: "氢气 (83%), 氦气 (15%), 甲烷 (2%)",
    moonCount: 27,
    discovery: "Herschel 1781",
    discoveryZh: "赫歇尔 1781",
  },
  neptune: {
    name: "Neptune",
    nameZh: "海王星",
    size: 0.9,
    orbitRadius: 30.07 * SCALE,
    orbitSpeed: (2 * Math.PI) / 60182.0,
    orbitalIncl: 1.77,
    axialTilt: 28.32,
    selfRotationSpeed: (2 * Math.PI) / 0.671,
    type: "planet",
    realAU: 30.07,
    realPeriod: 60182.0,
    realRadius: 24622,
    color: "#3355cc",
    emissiveHex: "#081040",
    emissiveIntensity: 0.22,
    description:
      "Windiest planet (2,100 km/h). Discovered mathematically (1846).",
    descriptionZh:
      "风速最快的行星（2,100 km/h）。通过数学预测发现（1846 年）。",
    mass: 17.15,
    gravity: 11.15,
    temperature: "-218 °C",
    atmosphere: "H₂ (80%), He (19%), CH₄ (1%)",
    atmosphereZh: "氢气 (80%), 氦气 (19%), 甲烷 (1%)",
    moonCount: 16,
    discovery: "Galle 1846 (predicted)",
    discoveryZh: "加勒 1846（数学预测）",
  },
  io: {
    name: "Io",
    nameZh: "木卫一",
    size: 0.08,
    orbitRadius: 3.5,
    orbitSpeed: (2 * Math.PI) / 1.77,
    orbitalIncl: 0.04,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 1.77,
    type: "moon",
    realAU: 0,
    realPeriod: 1.77,
    realRadius: 1821,
    color: "#e8d050",
    emissiveHex: "#3a3010",
    emissiveIntensity: 0.18,
    description:
      "Most volcanically active body. 400+ volcanoes. Orbital resonance with Europa & Ganymede (4:2:1).",
    descriptionZh:
      "太阳系火山活动最活跃的天体。400+ 座火山。与木卫二、木卫三形成 4:2:1 轨道共振。",
    mass: 0.015,
    gravity: 1.8,
    temperature: "-130 °C",
    atmosphere: "SO₂ (trace)",
    atmosphereZh: "二氧化硫（微量）",
    moonCount: 0,
    discovery: "Galileo 1610",
    discoveryZh: "伽利略 1610",
  },
  europa: {
    name: "Europa",
    nameZh: "木卫二",
    size: 0.07,
    orbitRadius: 5.0,
    orbitSpeed: (2 * Math.PI) / 3.55,
    orbitalIncl: 0.47,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 3.55,
    type: "moon",
    realAU: 0,
    realPeriod: 3.55,
    realRadius: 1561,
    color: "#e0ddd8",
    emissiveHex: "#3a3a35",
    emissiveIntensity: 0.15,
    description:
      "Icy crust. Subsurface global ocean. Prime target for astrobiology.",
    descriptionZh: "冰壳覆盖。存在地下全球性海洋。天体生物学首要探测目标。",
    mass: 0.008,
    gravity: 1.31,
    temperature: "-160 °C",
    atmosphere: "O₂ (trace)",
    atmosphereZh: "氧气（微量）",
    moonCount: 0,
    discovery: "Galileo 1610",
    discoveryZh: "伽利略 1610",
  },
  ganymede: {
    name: "Ganymede",
    nameZh: "木卫三",
    size: 0.12,
    orbitRadius: 7.0,
    orbitSpeed: (2 * Math.PI) / 7.15,
    orbitalIncl: 0.2,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 7.15,
    type: "moon",
    realAU: 0,
    realPeriod: 7.15,
    realRadius: 2634,
    color: "#c8c0b0",
    emissiveHex: "#302828",
    emissiveIntensity: 0.14,
    description:
      "Largest moon in Solar System. Only moon with intrinsic magnetic field.",
    descriptionZh: "太阳系最大的卫星。唯一拥有固有磁场的卫星。",
    mass: 0.025,
    gravity: 1.43,
    temperature: "-160 °C",
    atmosphere: "O₂ (trace)",
    atmosphereZh: "氧气（微量）",
    moonCount: 0,
    discovery: "Galileo 1610",
    discoveryZh: "伽利略 1610",
  },
  callisto: {
    name: "Callisto",
    nameZh: "木卫四",
    size: 0.1,
    orbitRadius: 9.0,
    orbitSpeed: (2 * Math.PI) / 16.69,
    orbitalIncl: 0.19,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 16.69,
    type: "moon",
    realAU: 0,
    realPeriod: 16.69,
    realRadius: 2410,
    color: "#706860",
    emissiveHex: "#1a1612",
    emissiveIntensity: 0.1,
    description:
      "Most heavily cratered body. Ancient surface (>4 Gyr). Valhalla multi-ring impact basin.",
    descriptionZh:
      "陨石坑密度最高的天体。古老表面（>40 亿年）。瓦尔哈拉多环撞击盆地。",
    mass: 0.018,
    gravity: 1.24,
    temperature: "-139 °C",
    atmosphere: "CO₂ (trace)",
    atmosphereZh: "二氧化碳（微量）",
    moonCount: 0,
    discovery: "Galileo 1610",
    discoveryZh: "伽利略 1610",
  },
  phobos: {
    name: "Phobos",
    nameZh: "火卫一",
    size: 0.045,
    orbitRadius: 1.3,
    orbitSpeed: (2 * Math.PI) / 0.31891,
    orbitalIncl: 1.093,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 0.31891,
    type: "moon",
    realAU: 0,
    realPeriod: 0.31891,
    realRadius: 11.1,
    color: "#8a7a6a",
    emissiveHex: "#1c1814",
    emissiveIntensity: 0.08,
    description:
      "Largest Mars moon. Captured asteroid. Spiraling toward Mars. Stickney crater (9 km).",
    descriptionZh:
      "火星第一大卫星。被捕获的小行星。正螺旋式靠近火星。斯蒂克尼陨石坑（9 km）。",
    mass: 0.0000018,
    gravity: 0.0057,
    temperature: "-40 °C",
    atmosphere: "None",
    atmosphereZh: "无",
    moonCount: 0,
    discovery: "Hall 1877",
    discoveryZh: "霍尔 1877",
  },
  deimos: {
    name: "Deimos",
    nameZh: "火卫二",
    size: 0.028,
    orbitRadius: 2.8,
    orbitSpeed: (2 * Math.PI) / 1.26244,
    orbitalIncl: 0.93,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 1.26244,
    type: "moon",
    realAU: 0,
    realPeriod: 1.26244,
    realRadius: 6.2,
    color: "#9a9088",
    emissiveHex: "#1e1c1a",
    emissiveIntensity: 0.06,
    description:
      "Smaller Mars moon. Captured asteroid. Smooth surface from regolith infill. Slowly receding from Mars.",
    descriptionZh:
      "火星较小卫星。被捕获的小行星。表面因表土层填充而光滑。正缓慢远离火星。",
    mass: 0.00000025,
    gravity: 0.003,
    temperature: "-40 °C",
    atmosphere: "None",
    atmosphereZh: "无",
    moonCount: 0,
    discovery: "Hall 1877",
    discoveryZh: "霍尔 1877",
  },
  mimas: {
    name: "Mimas",
    nameZh: "土卫一",
    size: 0.08,
    orbitRadius: 4.2,
    orbitSpeed: (2 * Math.PI) / 0.9424,
    orbitalIncl: 1.53,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 0.9424,
    type: "moon",
    realAU: 0,
    realPeriod: 0.9424,
    realRadius: 198,
    color: "#d0ccc8",
    emissiveHex: "#302e2c",
    emissiveIntensity: 0.1,
    description:
      "Smallest round Saturn moon. 130 km Herschel crater. 'Death Star' appearance. Icy body.",
    descriptionZh:
      '土星最小的圆形卫星。赫歇尔陨石坑直径 130 km。"死星"外观。冰质天体。',
    mass: 0.0000066,
    gravity: 0.064,
    temperature: "-209 °C",
    atmosphere: "None",
    atmosphereZh: "无",
    moonCount: 0,
    discovery: "Herschel 1789",
    discoveryZh: "赫歇尔 1789",
  },
  enceladus: {
    name: "Enceladus",
    nameZh: "土卫二",
    size: 0.11,
    orbitRadius: 5.4,
    orbitSpeed: (2 * Math.PI) / 1.3702,
    orbitalIncl: 0.0,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 1.3702,
    type: "moon",
    realAU: 0,
    realPeriod: 1.3702,
    realRadius: 252,
    color: "#e8f0f8",
    emissiveHex: "#2a3038",
    emissiveIntensity: 0.12,
    description:
      "Active icy moon. South pole geysers. Subsurface global ocean. E ring source. Reflects 99% sunlight.",
    descriptionZh:
      "活跃冰卫星。南极间歇泉喷发。存在地下全球海洋。E 环物质来源。反射 99% 阳光。",
    mass: 0.000018,
    gravity: 0.113,
    temperature: "-198 °C",
    atmosphere: "H₂O vapor (plumes)",
    atmosphereZh: "水蒸气（羽流）",
    moonCount: 0,
    discovery: "Herschel 1789",
    discoveryZh: "赫歇尔 1789",
  },
  tethys: {
    name: "Tethys",
    nameZh: "土卫三",
    size: 0.2,
    orbitRadius: 7.0,
    orbitSpeed: (2 * Math.PI) / 1.8878,
    orbitalIncl: 1.1,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 1.8878,
    type: "moon",
    realAU: 0,
    realPeriod: 1.8878,
    realRadius: 531,
    color: "#c8c4c0",
    emissiveHex: "#282624",
    emissiveIntensity: 0.09,
    description:
      "Medium icy Saturn moon. Odysseus crater (445 km). Ithaca Chasma tectonic trench. Low density (0.98 g/cm³).",
    descriptionZh:
      "中型土星冰卫星。奥德修斯陨石坑（445 km）。伊萨卡深谷构造裂缝。低密度（0.98 g/cm³）。",
    mass: 0.000103,
    gravity: 0.146,
    temperature: "-187 °C",
    atmosphere: "None",
    atmosphereZh: "无",
    moonCount: 0,
    discovery: "Cassini 1684",
    discoveryZh: "卡西尼 1684",
  },
  dione: {
    name: "Dione",
    nameZh: "土卫四",
    size: 0.22,
    orbitRadius: 8.8,
    orbitSpeed: (2 * Math.PI) / 2.7369,
    orbitalIncl: 0.0,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 2.7369,
    type: "moon",
    realAU: 0,
    realPeriod: 2.7369,
    realRadius: 561,
    color: "#d0ccc4",
    emissiveHex: "#2a2824",
    emissiveIntensity: 0.1,
    description:
      "Saturn moon with varied terrain. Wispy ice cliffs. Subsurface ocean suspected. Co-orbital with Helene & Polydeuces.",
    descriptionZh:
      "土星卫星，地形多样。条状冰崖。疑似存在地下海洋。与赫勒涅、波吕丢刻斯共轨。",
    mass: 0.000183,
    gravity: 0.232,
    temperature: "-186 °C",
    atmosphere: "O₂ (trace)",
    atmosphereZh: "氧气（微量）",
    moonCount: 0,
    discovery: "Cassini 1684",
    discoveryZh: "卡西尼 1684",
  },
  rhea: {
    name: "Rhea",
    nameZh: "土卫五",
    size: 0.28,
    orbitRadius: 12.0,
    orbitSpeed: (2 * Math.PI) / 4.5175,
    orbitalIncl: 0.3,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 4.5175,
    type: "moon",
    realAU: 0,
    realPeriod: 4.5175,
    realRadius: 764,
    color: "#ccc8c2",
    emissiveHex: "#282622",
    emissiveIntensity: 0.08,
    description:
      "Second largest Saturn moon. Heavily cratered icy body. Uniform surface. Possible thin ring system.",
    descriptionZh:
      "土星第二大卫星。重陨击冰质天体。表面均匀。可能存在稀薄环系统。",
    mass: 0.000386,
    gravity: 0.264,
    temperature: "-174 °C",
    atmosphere: "O₂/CO₂ (trace)",
    atmosphereZh: "氧气/二氧化碳（微量）",
    moonCount: 0,
    discovery: "Cassini 1672",
    discoveryZh: "卡西尼 1672",
  },
  titan: {
    name: "Titan",
    nameZh: "土卫六",
    size: 0.42,
    orbitRadius: 22.0,
    orbitSpeed: (2 * Math.PI) / 15.945,
    orbitalIncl: 0.3,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 15.945,
    type: "moon",
    realAU: 0,
    realPeriod: 15.945,
    realRadius: 2575,
    color: "#d4a860",
    emissiveHex: "#302818",
    emissiveIntensity: 0.1,
    description:
      "Largest Saturn moon. Thick nitrogen atmosphere (1.5 bar). Liquid methane lakes. Only moon with atmosphere. Huygens probe (2005).",
    descriptionZh:
      "土星最大卫星。浓厚氮气大气（1.5 bar）。液态甲烷湖泊。唯一拥有大气层的卫星。惠更斯探测器（2005 年）。",
    mass: 0.0225,
    gravity: 1.35,
    temperature: "-179 °C",
    atmosphere: "N₂ (95%), CH₄ (5%)",
    atmosphereZh: "氮气 (95%), 甲烷 (5%)",
    moonCount: 0,
    discovery: "Huygens 1655",
    discoveryZh: "惠更斯 1655",
  },
};

export const CAMERA_PRESETS = {
  free: { name: "Free Orbit", position: [0, 30, 50], target: [0, 0, 0] },
  topDown: { name: "Top Down", position: [0, 45, 0.5], target: [0, 0, 0] },
};

export const SCENE = {
  STAR_COUNT: 3000,
  STAR_RADIUS: 350,
  ORBIT_SEGMENTS: 256,
  ASTEROID_COUNT: 3000,
  ASTEROID_MIN_R: 1.6 * SCALE,
  ASTEROID_MAX_R: 4.5 * SCALE,
};
