// ============================================================
// constants.js — v10：修复水星遮挡 + 月球距离 + 真实地球贴图
// ============================================================
// Sun=3.0 < Mercury orbit=3.87 → 水星可见
// Moon orbitRadius=1.8 → 月球紧贴地球 (视觉合理)
// Earth 使用 NASA/Three.js 官方蓝色弹珠贴图
// ============================================================

export const SIM = {
  BASE_SPEED: 1.0,
  SPEED_STEP: 0.4,
  MIN_SPEED: 0.0,
  MAX_SPEED: 5.0,
  MAX_DELTA: 0.1,
  ROTATION_SPEED_SCALE: 0.03,
};

const SCALE = 10;

export const BODIES = {
  sun: {
    name: "Sun",
    size: 3.0,
    orbitRadius: 0,
    orbitSpeed: 0,
    orbitalIncl: 0,
    axialTilt: 7.25,
    selfRotationSpeed: (2 * Math.PI) / 25.05,
    type: "star",
    realAU: 0,
    realPeriod: 0,
    realRadius: 696340,
    color: "#fffbe0",
    emissiveHex: null,
    emissiveIntensity: 0,
    description:
      "G-type main-sequence star (G2V). Surface temp: 5,778 K. 99.86% of Solar System mass.",
  },
  mercury: {
    name: "Mercury",
    size: 0.22,
    orbitRadius: 0.387 * SCALE,
    orbitSpeed: (2 * Math.PI) / 88.0,
    orbitalIncl: 7.0,
    axialTilt: 0.03,
    selfRotationSpeed: (2 * Math.PI) / 58.6,
    type: "planet",
    realAU: 0.387,
    realPeriod: 88.0,
    realRadius: 2440,
    color: "#b0a090",
    emissiveHex: "#3a3028",
    emissiveIntensity: 0.18,
    description:
      "Smallest planet. No atmosphere. Temperature range: -180°C to 430°C.",
  },
  venus: {
    name: "Venus",
    size: 0.6,
    orbitRadius: 0.723 * SCALE,
    orbitSpeed: (2 * Math.PI) / 224.7,
    orbitalIncl: 3.4,
    axialTilt: 177.4,
    selfRotationSpeed: (2 * Math.PI) / 243.0,
    type: "planet",
    realAU: 0.723,
    realPeriod: 224.7,
    realRadius: 6052,
    color: "#e8d5a8",
    emissiveHex: "#5a4a28",
    emissiveIntensity: 0.22,
    description:
      "Hottest planet (462°C). Thick CO₂ atmosphere. Retrograde rotation.",
  },
  earth: {
    name: "Earth",
    size: 0.65,
    orbitRadius: 1.0 * SCALE,
    orbitSpeed: (2 * Math.PI) / 365.25,
    orbitalIncl: 0.0,
    axialTilt: 23.44,
    selfRotationSpeed: (2 * Math.PI) / 1.0,
    type: "planet",
    realAU: 1.0,
    realPeriod: 365.25,
    realRadius: 6371,
    color: "#1a6fb5",
    emissiveHex: "#0a2255",
    emissiveIntensity: 0.2,
    description:
      "Only known planet with life. 71% ocean. Atmosphere: N₂ 78%, O₂ 21%.",
  },
  moon: {
    name: "Moon",
    size: 0.18,
    orbitRadius: 1.8,
    orbitSpeed: (2 * Math.PI) / 27.3,
    orbitalIncl: 5.14,
    axialTilt: 6.68,
    selfRotationSpeed: (2 * Math.PI) / 27.3,
    type: "moon",
    realAU: 0,
    realPeriod: 27.3,
    realRadius: 1737,
    color: "#aaaaaa",
    emissiveHex: "#2a2a2a",
    emissiveIntensity: 0.12,
    description:
      "Earth only natural satellite. Tidally locked. Basaltic maria + anorthositic highlands.",
  },
  mars: {
    name: "Mars",
    size: 0.4,
    orbitRadius: 1.524 * SCALE,
    orbitSpeed: (2 * Math.PI) / 687.0,
    orbitalIncl: 1.85,
    axialTilt: 25.19,
    selfRotationSpeed: (2 * Math.PI) / 1.026,
    type: "planet",
    realAU: 1.524,
    realPeriod: 687.0,
    realRadius: 3390,
    color: "#c1440e",
    emissiveHex: "#401208",
    emissiveIntensity: 0.2,
    description: "Red Planet. Iron oxide surface. Olympus Mons (21.9 km).",
  },
  jupiter: {
    name: "Jupiter",
    size: 1.8,
    orbitRadius: 5.203 * SCALE,
    orbitSpeed: (2 * Math.PI) / 4332.6,
    orbitalIncl: 1.3,
    axialTilt: 3.13,
    selfRotationSpeed: (2 * Math.PI) / 0.414,
    type: "planet",
    realAU: 5.203,
    realPeriod: 4332.6,
    realRadius: 69911,
    color: "#d4a574",
    emissiveHex: "#3a2210",
    emissiveIntensity: 0.15,
    description: "Largest planet. Great Red Spot: 350+ years. 95 known moons.",
  },
  saturn: {
    name: "Saturn",
    size: 1.55,
    orbitRadius: 9.537 * SCALE,
    orbitSpeed: (2 * Math.PI) / 10759.2,
    orbitalIncl: 2.5,
    axialTilt: 26.73,
    selfRotationSpeed: (2 * Math.PI) / 0.444,
    type: "planet",
    realAU: 9.537,
    realPeriod: 10759.2,
    realRadius: 58232,
    color: "#e8d5a0",
    emissiveHex: "#4a3820",
    emissiveIntensity: 0.16,
    description: "Famous ring system (ice+rock). Least dense planet.",
  },
  uranus: {
    name: "Uranus",
    size: 0.95,
    orbitRadius: 19.19 * SCALE,
    orbitSpeed: (2 * Math.PI) / 30688.5,
    orbitalIncl: 0.77,
    axialTilt: 97.77,
    selfRotationSpeed: (2 * Math.PI) / 0.718,
    type: "planet",
    realAU: 19.19,
    realPeriod: 30688.5,
    realRadius: 25362,
    color: "#7ec8e3",
    emissiveHex: "#0a3040",
    emissiveIntensity: 0.18,
    description: "Ice giant. Rotates on its side (98°). Methane → cyan color.",
  },
  neptune: {
    name: "Neptune",
    size: 0.9,
    orbitRadius: 30.07 * SCALE,
    orbitSpeed: (2 * Math.PI) / 60182.0,
    orbitalIncl: 1.77,
    axialTilt: 28.32,
    selfRotationSpeed: (2 * Math.PI) / 0.671,
    type: "planet",
    realAU: 30.07,
    realPeriod: 60182.0,
    realRadius: 24622,
    color: "#3355cc",
    emissiveHex: "#081040",
    emissiveIntensity: 0.22,
    description:
      "Windiest planet (2,100 km/h). Discovered mathematically (1846).",
  },
  io: {
    name: "Io",
    size: 0.08,
    orbitRadius: 3.5,
    orbitSpeed: (2 * Math.PI) / 1.77,
    orbitalIncl: 0.04,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 1.77,
    type: "moon",
    realAU: 0,
    realPeriod: 1.77,
    realRadius: 1821,
    color: "#e8d050",
    emissiveHex: "#3a3010",
    emissiveIntensity: 0.18,
    description:
      "Most volcanically active body. 400+ volcanoes. Orbital resonance with Europa & Ganymede (4:2:1).",
  },
  europa: {
    name: "Europa",
    size: 0.07,
    orbitRadius: 5.0,
    orbitSpeed: (2 * Math.PI) / 3.55,
    orbitalIncl: 0.47,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 3.55,
    type: "moon",
    realAU: 0,
    realPeriod: 3.55,
    realRadius: 1561,
    color: "#e0ddd8",
    emissiveHex: "#3a3a35",
    emissiveIntensity: 0.15,
    description:
      "Icy crust. Subsurface global ocean. Prime target for astrobiology.",
  },
  ganymede: {
    name: "Ganymede",
    size: 0.12,
    orbitRadius: 7.0,
    orbitSpeed: (2 * Math.PI) / 7.15,
    orbitalIncl: 0.2,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 7.15,
    type: "moon",
    realAU: 0,
    realPeriod: 7.15,
    realRadius: 2634,
    color: "#c8c0b0",
    emissiveHex: "#302828",
    emissiveIntensity: 0.14,
    description:
      "Largest moon in Solar System. Only moon with intrinsic magnetic field.",
  },
  callisto: {
    name: "Callisto",
    size: 0.1,
    orbitRadius: 9.0,
    orbitSpeed: (2 * Math.PI) / 16.69,
    orbitalIncl: 0.19,
    axialTilt: 0,
    selfRotationSpeed: (2 * Math.PI) / 16.69,
    type: "moon",
    realAU: 0,
    realPeriod: 16.69,
    realRadius: 2410,
    color: "#706860",
    emissiveHex: "#1a1612",
    emissiveIntensity: 0.1,
    description:
      "Most heavily cratered body. Ancient surface (>4 Gyr). Valhalla multi-ring impact basin.",
  },
};

export const CAMERA_PRESETS = {
  free: { name: "Free Orbit", position: [0, 30, 50], target: [0, 0, 0] },
  topDown: { name: "Top Down", position: [0, 45, 0.5], target: [0, 0, 0] },
  followEarth: {
    name: "Follow Earth",
    position: [2, 1.5, 4],
    target: [0, 0, 0],
    isDynamic: true,
  },
  sunView: { name: "Sun View", position: [2, 1.5, 6], target: [0, 0, 0] },
};

export const SCENE = {
  STAR_COUNT: 3000,
  STAR_RADIUS: 350,
  ORBIT_SEGMENTS: 256,
  ASTEROID_COUNT: 3000,
  ASTEROID_MIN_R: 1.6 * SCALE,
  ASTEROID_MAX_R: 4.5 * SCALE,
};
